#define LINEINTERSECTSWITH_LENGTH 0.1


#define ALM_MAX_ELEVATION 0
#define ALM_MIN_ELEVATION -2

#define ABM_MAX_ELEVATION 2
#define ABM_MIN_ELEVATION -2


#define ALM_MIN_VECTORUP 0.93


#define HOTKEY_ELEVATION_CHANGE_RATE 1
#define HOTKEY_DISTANCE_CHANGE_RATE 5

// #define SWITCH_TO_ABM_HEIGHT 1000000

#define MAX_FORT_DISTANCE 20

#define MIN_DISTANCE_TO_ANOTHER_FORT 0.3



#define BS_POST_WARBEGIN_TIMEOUT 300

